version: '3'
services:
    mongo-container:
      image: mongo:latest
      container_name: 'Manager-Mongo'
      ports:
        - "27017:27017"
      volumes:
        - "/home/don/Docker/mongo/:/docker-entrypoint-initdb.d/"
      command: mongod

    website:
      image: url_shortener:latest
      container_name: 'url_shortener'
      volumes:
        - "/home/don/Docker/web/:/var/www/html/Webinterface"
      ports:
        - "80:80"
      command: /usr/sbin/apache2ctl -D FOREGROUND
    
